### ISSUE TITLE
Error running Drizzle Studio

### ISSUE THREAD

**Issue by myty** [myty/deno-drizzle-demo#2]
Running `deno task studio` currently results in the following error with the first request:

```sh
Terminating Deno.serve loop due to unexpected error TypeError: Cannot read properties of undefined (reading 'status')
    at ext:deno_http/00_serve.ts:410:26
    at eventLoopTick (ext:core/01_core.js:175:7)
```

**Comment by sathirak** [comment]
@myty Hey man thanks for your work, really helped me get drizzle into Deno, running into the same drizzle-kit studio issue currently. 

Great Work!

**Comment by myty** [comment]
> @myty Hey man thanks for your work, really helped me get drizzle into Deno, running into the same drizzle-kit studio issue currently.
> 
> Great Work!

Thank you for the kind words and I'm super glad it's helping you out! 

I should soon be able to do a deep dive and hopefully get this working.

**Comment by myty** [comment]
Looks like someone else reported this with `drizzle-kit`: https://github.com/drizzle-team/drizzle-kit-mirror/issues/394#issuecomment-2347082253

**Comment by sathirak** [comment]
@myty  Oh that nice!

**Comment by Pyakz** [comment]
were are able to run the studio, guys?

**Comment by myty** [comment]
@Pyakz Unfortunately, I haven't been able to produce a workaround yet. I've upgraded drizzle-kit and Deno to the latest versions and still get this:

```sh
Task drizzle-kit deno run --env -A --node-modules-dir npm:drizzle-kit "studio"
No config path provided, using default 'drizzle.config.ts'
Reading config file '***************/deno-drizzle-demo/drizzle.config.ts'
Failed to find Response internal state key
Using 'postgres' driver for database querying
```

I believe the key error is this line: `Failed to find Response internal state key`

**Comment by myty** [comment]
This works now with the release of Deno `v2.3.1`: https://github.com/denoland/deno/issues/28022#issuecomment-2843905482
